tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'

brew 'postgresql', restart_service: true

brew 'ack'
brew 'autojump'
brew 'yarn'
brew 'ruby-build'
brew 'rbenv'
brew 'wget'
brew 'curl'
brew 'heroku'
brew 'diff-so-fancy'
brew 'tmate'
brew 'git'

brew 'zsh'
brew 'bash'
brew 'bash-completion'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'

brew 'libyaml'
brew 'openssl'
brew 'readline'
brew 'autoconf'

brew 'libpng'
brew 'jpeg'
brew 'freetype'
brew 'fontconfig'
brew 'gettext'
brew 'libffi'
brew 'glib'
brew 'ffmpeg'
brew 'libtool'
brew 'webp'
brew 'imagemagick', args: ['with-webp']
brew 'libssh'
brew 'libxml2'
brew 'libxslt'
brew 'openjpeg'
brew 'webkit2png'
brew 'exa'
brew 'bat'
brew 'prettyping'
brew 'fzf'
brew 'ncdu'

brew 'cmake'
brew 'coreutils'
