palette = "main"

format = """$directory$git_branch$git_status$elixir$erlang$nodejs$rust$golang$python$ruby$lua$java$kotlin$c$swift$zig$line_break$character"""

right_format = """$cmd_duration"""

[palettes.main]
dir = "#286983"
git = "#56949f"
git_status = "#b4637a"
lang = "#907aa9"
sep = "#9893a5"
info = "#797593"

[character]
success_symbol = '[➜](fg:green)'
error_symbol = '[✗](fg:red)'

[directory]
format = '[$path$read_only](fg:dir)[  ](fg:sep)'
read_only = " 󰌾"
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = '[$symbol$branch](fg:git)'
symbol = " "

[git_status]
format = '[ $all_status$ahead_behind](fg:git_status)[  ](fg:sep)'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[git_commit]
tag_symbol = '  '

[elixir]
format = '[$symbol$version](fg:lang)'
symbol = " "

[erlang]
format = '[$symbol$version](fg:lang)'
symbol = " "

[nodejs]
format = '[$symbol$version](fg:lang)'
symbol = " "

[rust]
format = '[$symbol$version](fg:lang)'
symbol = "󱘗 "

[golang]
format = '[$symbol$version](fg:lang)'
symbol = " "

[python]
format = '[$symbol$version](fg:lang)'
symbol = " "

[ruby]
format = '[$symbol$version](fg:lang)'
symbol = " "

[lua]
format = '[$symbol$version](fg:lang)'
symbol = " "

[java]
format = '[$symbol$version](fg:lang)'
symbol = " "

[kotlin]
format = '[$symbol$version](fg:lang)'
symbol = " "

[c]
format = '[$symbol$version](fg:lang)'
symbol = " "

[swift]
format = '[$symbol$version](fg:lang)'
symbol = " "

[zig]
format = '[$symbol$version](fg:lang)'
symbol = " "

[cmd_duration]
format = '[󰔟 $duration](fg:info)'
min_time = 2_000

[aws]
disabled = true

[buf]
disabled = true

[package]
disabled = true

[julia]
disabled = true

[nix_shell]
disabled = true

[docker_context]
symbol = " "

[hostname]
ssh_symbol = " "
