format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$kubernetes\
$hg_branch\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$container\
$shell\
$character"""

[directory]
style = "blue"
truncate_to_repo = false
truncation_length = 0

[git_branch]
symbol = ""
style = "green"

[git_status]
style = "red"

[elixir]
disabled = true

[package]
disabled = true

[character]
disabled = false
success_symbol = '[❯](fg:green)'
error_symbol = '[❯](fg:red)'

[ruby]
disabled = true

[nodejs]
disabled = true

[docker_context]
disabled = true

[gcloud]
disabled = true

[terraform]
disabled = true

[golang]
disabled = true

[vagrant]
disabled = true
