[directory]
style = "blue"
truncate_to_repo = false
truncation_length = 0

[git_branch]
symbol = ""
style = "green"

[git_status]
style = "red"

[elixir]
disabled = true

[package]
disabled = true

[character]
success_symbol = "[➜](bold green)"

[ruby]
disabled = true
